### PR TITLE
Fix: correct info on merge commits (closes #1)

### LINKED ISSUE #1: Returning {} for Merge commits
It is returning {} for merge commits.

### PR DESCRIPTION
**Pull request by valerit**
this resolves #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -49,6 +50,7 @@ const gitCommitInfo = ({ cwd, commit } = {}) => {
       message,
     };
   } catch (e) {
+    console.info(e);
```
Comment (JPeer264) [inline index.js]: Actually pretty nice to have that 👍

**Comment by JPeer264** [comment]
@valerit thanks for your PR. This just works, can you write a test for it? In the folders `./test/fixtures/*` are some git folders in it. You can just add some commits there, or add an additional git directory.

**Comment by JPeer264** [comment]
Can you maybe also remove the `package-lock`. In this project I am using yarn - so managing two lock files is a bit too much.

**Comment by JPeer264** [comment]
@valerit if it is ok for you, I would take over from here and add tests - then we can merge this PR

**Comment by JPeer264** [comment]
@valerit this is now fixed in `v1.0.1`
